# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apartments' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apartments
  pod 'Alamofire', '~> 4.7'
  pod 'Strongbox', '~> 0.5.1'
  pod 'SwiftyJSON', '~> 4.1.0'
  pod 'AZTableView', '0.0.3'
  pod 'Eureka', '4.2.0'

  target 'ApartmentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApartmentsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
